language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  - cabal install Cabal
  - cabal install 'case-insensitive >=0.4.0.1 && < 1.3'
  - cabal install 'monadcatchio-transformers >=0.3.0.0 && < 0.4'
  - cabal install 'zlib >=0.5.3.3 && <0.6'
  - cabal install 'utf8-string >=0.3.7 && <0.4'
  - cabal install 'attoparsec >=0.10.1.1 && <0.13'
  - cabal install 'hunit >=1.2.4.2 && <1.3'
  - cabal install 'lens >=3.10 && <=4.13.1'
  - cabal install 'quickcheck >=2.4.2 && <2.8'
  - cabal install base64-bytestring
  - cabal install crypto
  - cabal install curl
  - cabal install hinotify
  - cabal install hslogger
  - cabal install json
  - cabal install lifted-base
  - cabal install network
  - cabal install parallel
  - cabal install psqueue
  - cabal install regex-pcre
  - cabal install temporary
  - cabal install test-framework
  - cabal install test-framework-hunit
  - cabal install test-framework-quickcheck2
  - cabal install text
  - cabal install vector

script:
  - ./autogen.sh && ./configure --enable-haskell-tests && make
  - make hs-tests
  - make py-tests

addons:
  apt:
    packages:
      - bridge-utils
      - fping
      - iproute
      - iputils-arping
      - lvm2
      - m4
      - make
      - ndisc6
      - openssl
      - python
      - python-bitarray
      - python-ipaddr
      - python-openssl
      - python-pycurl
      - python-pyinotify
      - python-pyparsing
      - python-simplejson
      - socat
      - ssh
      - python-paramiko
      - python-psutil
      - qemu-utils
      - fakeroot
      - graphviz
      - pandoc
      - python-epydoc
      - python-setuptools
      - python-sphinx
      - python-yaml
      - python-mock
      - pep8
      - pylint
      - hlint
      - hscolour
      - libpcre3-dev