language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  - cabal install Cabal && cabal update
  - cabal configure --enable-tests cabal/ganeti.template.cabal
  - cabal install --only-dependencies --enable-tests cabal/ganeti.template.cabal

script:
  - cabal configure --enable-tests cabal/ganeti.template.cabal
  - ./autogen.sh && ./configure --enable-haskell-tests && make
  - make hs-tests
  - make py-tests

addons:
  apt:
    packages:
      - bridge-utils
      - fping
      - iproute
      - iputils-arping
      - lvm2
      - m4
      - make
      - ndisc6
      - openssl
      - python
      - python-bitarray
      - python-ipaddr
      - python-openssl
      - python-pycurl
      - python-pyinotify
      - python-pyparsing
      - python-simplejson
      - socat
      - ssh
      - python-paramiko
      - python-psutil
      - qemu-utils
      - fakeroot
      - graphviz
      - pandoc
      - python-epydoc
      - python-setuptools
      - python-sphinx
      - python-yaml
      - python-mock
      - pep8
      - pylint
      - hlint
      - hscolour
      - libpcre3-dev