language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  - cabal install attoparsec
  - cabal install base64-bytestring
  - cabal install crypto
  - cabal install curl
  - cabal install hinotify
  - cabal install hslogger
  - cabal install hunit
  - cabal install json
  - cabal install lens
  - cabal install lifted-base
  - cabal install network
  - cabal install parallel
  - cabal install psqueue
  - cabal install quickcheck
  - cabal install regex-pcre
  - cabal install snap-server
  - cabal install temporary
  - cabal install test-framework
  - cabal install test-framework-hunit
  - cabal install test-framework-quickcheck2
  - cabal install text
  - cabal install utf8-string
  - cabal install vector
  - cabal install zlib

script:
  - ./autogen.sh && ./configure --enable-haskell-tests && make
  - make hs-tests
  - make py-tests

addons:
  apt:
    packages:
      - bridge-utils
      - fping
      - iproute
      - iputils-arping
      - lvm2
      - m4
      - make
      - ndisc6
      - openssl
      - python
      - python-bitarray
      - python-ipaddr
      - python-openssl
      - python-pycurl
      - python-pyinotify
      - python-pyparsing
      - python-simplejson
      - socat
      - ssh
      - python-paramiko
      - python-psutil
      - qemu-utils
      - fakeroot
      - graphviz
      - pandoc
      - python-epydoc
      - python-setuptools
      - python-sphinx
      - python-yaml
      - python-mock
      - pep8
      - pylint
      - hlint
      - hscolour
      - libpcre3-dev